name: Build and Publish

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Fetch Unity Explorer files
        run: |
          wget https://github.com/sinai-dev/UnityExplorer/releases/latest/download/UnityExplorer.Standalone.Mono.zip -O UnityExplorer.zip
          unzip UnityExplorer.zip -d References
      - name: Build project
        run: dotnet build --configuration Release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./bin/Publish/ReleaseInfo.txt
          files: |
            ./bin/Publish/Publish.zip